camel:
  lra:
    enabled: true
    coordinator-url: ${COORDINATOR_SERVICE_PROTO:http}://${COORDINATOR_SERVICE_HOST:localhost}:${COORDINATOR_SERVICE_PORT:8088}
    local-participant-url: ${LOCAL_PARTICIPANT_URL_PROTO:http}://${LOCAL_PARTICIPANT_URL_HOST:localhost}:${LOCAL_PARTICIPANT_URL_PORT:9081}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq-poc}       # RabbitMQ server host
#    host: ${RABBITMQ_HOST:localhost}       # RabbitMQ server host
    port: ${RABBITMQ_PORT:5672}            # RabbitMQ server port
    username: ${RABBITMQ_USERNAME:guest}   # RabbitMQ username
    password: ${RABBITMQ_PASSWORD:guest}   # RabbitMQ password
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/} # RabbitMQ virtual host

server:
  port: 9081

#logging:
#  level:
#    org:
#      springframework.amqp: DEBUG
#      apache:
#        camel: DEBUG